# Generated by Django 6.1.1 on 2026-09-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NodeSetting',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'node_setting',
            },
        ),
        migrations.CreateModel(
            name='NodeSetupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('initial', 'Initial setup'), ('reconfigure', 'Reconfiguration')], max_length=16)),
                ('state', models.CharField(choices=[('reading_node', 'Reading the node'), ('awaiting_reset_confirmation', 'Awaiting the reset confirmation'), ('resetting', 'Resetting'), ('awaiting_configuration', 'Awaiting the configuration'), ('configuring', 'Configuring'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='reading_node', max_length=40)),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('original_node_information', models.JSONField(blank=True, default=None, null=True)),
                ('original_public_key', models.CharField(blank=True, default='', max_length=64)),
                ('new_public_key', models.CharField(blank=True, default='', max_length=64)),
                ('requested_configuration', models.JSONField(blank=True, default=None, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'node_setup_runs',
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('is_active', True), models.Q(('state__in', ['completed', 'abandoned']), _negated=True)), models.Q(('is_active', False), ('state__in', ['completed', 'abandoned'])), _connector='OR'), name='node_setup_run_active_matches_state'), models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='node_setup_single_active_run')],
            },
        ),
        migrations.CreateModel(
            name='NodeCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('read_node_information', 'Read node information'), ('factory_reset', 'Factory reset'), ('configure_node', 'Configure node'), ('apply_configured_settings', 'Apply configured settings'), ('reboot_node', 'Reboot node'), ('send_advert', 'Send advert'), ('export_contact_card', 'Export contact card'), ('start_pairing', 'Start pairing'), ('stop_pairing', 'Stop pairing'), ('reconcile_contacts', 'Reconcile contacts')], max_length=40)),
                ('arguments', models.JSONField(default=dict)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('interrupted', 'Interrupted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('claimed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('claimed_by_worker_instance', models.UUIDField(blank=True, default=None, null=True)),
                ('progress', models.JSONField(default=list)),
                ('result', models.JSONField(blank=True, default=None, null=True)),
                ('error_message', models.TextField(blank=True, default='')),
                ('setup_run', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='node_commands', to='node.nodesetuprun')),
            ],
            options={
                'db_table': 'node_commands',
            },
        ),
        migrations.CreateModel(
            name='PairingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('stopped', 'Stopped')], default='active', max_length=16)),
                ('started_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('advert_interval_seconds', models.PositiveSmallIntegerField(default=30)),
                ('adverts_sent', models.PositiveIntegerField(default=0)),
                ('advert_flood', models.BooleanField(default=False)),
                ('last_advert_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('start_command', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='node.nodecommand')),
            ],
            options={
                'db_table': 'pairing_sessions',
            },
        ),
        migrations.CreateModel(
            name='HeardAdvert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('node_type', models.PositiveSmallIntegerField()),
                ('advert_timestamp', models.BigIntegerField()),
                ('latitude_microdegrees', models.IntegerField(default=0)),
                ('longitude_microdegrees', models.IntegerField(default=0)),
                ('contact_record', models.JSONField()),
                ('first_heard_at', models.DateTimeField()),
                ('last_heard_at', models.DateTimeField()),
                ('heard_count', models.PositiveIntegerField(default=1)),
                ('added_contact', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.contact')),
                ('pairing_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heard_adverts', to='node.pairingsession')),
            ],
            options={
                'db_table': 'heard_adverts',
            },
        ),
        migrations.CreateModel(
            name='WorkerStatus',
            fields=[
                ('id', models.SmallIntegerField(default=1, primary_key=True, serialize=False)),
                ('worker_instance_id', models.UUIDField(blank=True, default=None, null=True)),
                ('process_started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('relay_mode', models.CharField(choices=[('disconnected', 'Disconnected'), ('not_configured', 'Not configured'), ('setup_in_progress', 'Setup in progress'), ('identity_mismatch', 'Identity mismatch'), ('running', 'Running')], default='disconnected', max_length=24)),
                ('connection_state', models.CharField(choices=[('disconnected', 'Disconnected'), ('connecting', 'Connecting'), ('handshaking', 'Handshaking'), ('connected', 'Connected')], default='disconnected', max_length=16)),
                ('connection_generation', models.IntegerField(default=0)),
                ('connected_since', models.DateTimeField(blank=True, default=None, null=True)),
                ('transport_description', models.CharField(blank=True, default='', max_length=128)),
                ('node_public_key', models.CharField(blank=True, default='', max_length=64)),
                ('node_name', models.CharField(blank=True, default='', max_length=64)),
                ('node_firmware_version', models.CharField(blank=True, default='', max_length=64)),
                ('node_model', models.CharField(blank=True, default='', max_length=64)),
                ('node_protocol_version', models.IntegerField(blank=True, default=None, null=True)),
                ('node_contact_count', models.IntegerField(blank=True, default=None, null=True)),
                ('node_clock_offset_seconds', models.IntegerField(blank=True, default=None, null=True)),
                ('node_radio_summary', models.CharField(blank=True, default='', max_length=128)),
                ('settings_drift', models.JSONField(blank=True, default=list)),
                ('effective_configuration', models.JSONField(blank=True, default=dict)),
                ('packets_awaiting_node_acknowledgement', models.IntegerField(default=0)),
                ('replies_queued', models.IntegerField(default=0)),
                ('deliveries_due', models.IntegerField(default=0)),
                ('receipts_due', models.IntegerField(default=0)),
                ('pending_route_resets', models.IntegerField(default=0)),
                ('consecutive_connect_failures', models.IntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True, default='')),
                ('last_error_at', models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                'verbose_name_plural': 'worker status',
                'db_table': 'worker_status',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='worker_status_single_row')],
            },
        ),
        migrations.AddIndex(
            model_name='nodecommand',
            index=models.Index(condition=models.Q(('state', 'pending')), fields=['created_at'], name='node_command_pending_created'),
        ),
        migrations.AddIndex(
            model_name='nodecommand',
            index=models.Index(fields=['kind', 'created_at'], name='node_command_kind_created'),
        ),
        migrations.AddConstraint(
            model_name='nodecommand',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state__in', ['succeeded', 'failed', 'interrupted', 'expired', 'cancelled']), _negated=True), ('finished_at__isnull', False), _connector='OR'), name='node_command_terminal_state_has_finished_at'),
        ),
        migrations.AddConstraint(
            model_name='nodecommand',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='node_command_expires_after_creation'),
        ),
        migrations.AddConstraint(
            model_name='nodecommand',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'running')), fields=('state',), name='node_command_single_running'),
        ),
        migrations.AddConstraint(
            model_name='pairingsession',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('state',), name='pairing_single_active_session'),
        ),
        migrations.AddConstraint(
            model_name='heardadvert',
            constraint=models.UniqueConstraint(fields=('pairing_session', 'public_key'), name='heard_advert_unique_key_per_session'),
        ),
    ]
