# Generated by Django 6.1.1 on 2026-09-26 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('node', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodesetuprun',
            name='restored_public_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='workerstatus',
            name='node_identity_backup_state',
            field=models.CharField(choices=[('not_checked', 'Not checked'), ('stored', 'Stored'), ('missing', 'Missing'), ('unreadable', 'Unreadable'), ('export_disabled', 'Export disabled in the firmware'), ('failed', 'Failed')], default='not_checked', max_length=16),
        ),
    ]
