# Generated by Django 6.1.1 on 2026-09-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_address', models.GenericIPAddressField(blank=True, null=True)),
                ('succeeded', models.BooleanField()),
                ('attempted_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'operator_login_attempts',
                'indexes': [models.Index(fields=['client_address', 'attempted_at'], name='login_attempt_address_time')],
            },
        ),
    ]
