# Generated by Django 6.1.1 on 2026-09-25 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundDirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField()),
                ('sender_public_key_prefix', models.CharField(max_length=12)),
                ('contact_label', models.CharField(blank=True, default='', max_length=96)),
                ('sender_timestamp', models.BigIntegerField()),
                ('text_type', models.PositiveSmallIntegerField()),
                ('path_length', models.PositiveSmallIntegerField()),
                ('signal_to_noise_ratio', models.FloatField(blank=True, default=None, null=True)),
                ('text', models.TextField()),
                ('text_sha256', models.CharField(max_length=64)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('last_duplicate_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('classification', models.CharField(choices=[('unclassified', 'Unclassified'), ('request', 'Request'), ('acknowledgement', 'Acknowledgement'), ('not_protocol', 'Not protocol'), ('unsupported_version', 'Unsupported version'), ('syntax_error', 'Syntax error'), ('server_type_ignored', 'Server type ignored'), ('unknown_sender', 'Unknown sender'), ('unsupported_text_type', 'Unsupported text type')], default='unclassified', max_length=24)),
                ('request_type', models.CharField(blank=True, default='', max_length=1)),
                ('processing_state', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('failed', 'Failed')], default='received', max_length=16)),
                ('processing_error', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('outcome_summary', models.CharField(blank=True, default='', max_length=200)),
                ('reply_summary', models.CharField(blank=True, default='', max_length=160)),
                ('route_reset_performed', models.BooleanField(default=False)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_direct_messages', to='directory.contact')),
            ],
            options={
                'db_table': 'inbound_direct_messages',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_message_id', models.BigIntegerField()),
                ('part_count', models.PositiveSmallIntegerField()),
                ('part_texts', models.JSONField()),
                ('text', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('last_part_at', models.DateTimeField()),
                ('accepted_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('read_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='directory.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='directory.user')),
                ('sender_device', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='directory.contact')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='MessageDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('queued_for_refresh', 'Queued for a refresh'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=24)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('maximum_attempts', models.PositiveSmallIntegerField()),
                ('arm_generation', models.PositiveIntegerField(default=1)),
                ('next_attempt_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('round_pending_parts_mask', models.PositiveSmallIntegerField(default=0)),
                ('parts_received_mask', models.PositiveSmallIntegerField(default=0)),
                ('round_started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_acknowledgement_received_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('read_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failure_reason', models.CharField(blank=True, choices=[('attempts_exhausted', 'Attempts exhausted'), ('refresh_stopped', 'Refresh stopped')], default='', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='directory.contact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='messaging.message')),
            ],
            options={
                'verbose_name_plural': 'message deliveries',
                'db_table': 'message_deliveries',
            },
        ),
        migrations.CreateModel(
            name='ReceiptNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_level', models.PositiveSmallIntegerField(choices=[(1, 'Delivered'), (2, 'Read')])),
                ('confirmed_level', models.PositiveSmallIntegerField(choices=[(0, 'Nothing'), (1, 'Delivered'), (2, 'Read')], default=0)),
                ('state', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('maximum_attempts', models.PositiveSmallIntegerField()),
                ('arm_generation', models.PositiveIntegerField(default=1)),
                ('round_pending', models.BooleanField(default=False)),
                ('next_attempt_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('round_started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_confirmation_received_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failed_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_notifications', to='directory.contact')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_notifications', to='messaging.message')),
            ],
            options={
                'db_table': 'receipt_notifications',
            },
        ),
        migrations.CreateModel(
            name='OutboundPacket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_label', models.CharField(max_length=96)),
                ('purpose', models.CharField(choices=[('reply', 'Reply'), ('delivery', 'Delivery'), ('receipt', 'Receipt')], max_length=16)),
                ('part_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('receipt_level', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('arm_generation', models.PositiveIntegerField(blank=True, null=True)),
                ('attempt_number', models.PositiveIntegerField(blank=True, null=True)),
                ('reply_key', models.CharField(blank=True, default='', max_length=64)),
                ('text', models.TextField()),
                ('sender_timestamp', models.BigIntegerField(unique=True)),
                ('state', models.CharField(choices=[('prepared', 'Prepared'), ('queued_on_node', 'Queued on the node'), ('node_acknowledged', 'Acknowledged by the node'), ('acknowledgement_timed_out', 'Acknowledgement timed out'), ('rejected_by_node', 'Rejected by the node'), ('outcome_unknown', 'Outcome unknown')], default='prepared', max_length=32)),
                ('route', models.CharField(blank=True, choices=[('flood', 'Flood'), ('direct', 'Direct')], default='', max_length=8)),
                ('expected_acknowledgement_code', models.CharField(blank=True, default='', max_length=8)),
                ('suggested_timeout_milliseconds', models.PositiveIntegerField(blank=True, null=True)),
                ('prepared_at', models.DateTimeField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledgement_deadline_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('round_trip_milliseconds', models.PositiveIntegerField(blank=True, null=True)),
                ('node_error_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('route_reset_state', models.CharField(choices=[('not_applicable', 'Not applicable'), ('pending', 'Pending'), ('performed', 'Performed'), ('skipped_path_update', 'Skipped: the route changed'), ('skipped_application_evidence', 'Skipped: the device answered'), ('skipped_late_acknowledgement', 'Skipped: a late acknowledgement'), ('dropped_by_restart', 'Dropped by a restart')], default='not_applicable', max_length=32)),
                ('route_reset_decided_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('connection_generation', models.PositiveIntegerField()),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_packets', to='directory.contact')),
                ('message_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_packets', to='messaging.messagedelivery')),
                ('receipt_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_packets', to='messaging.receiptnotification')),
            ],
            options={
                'db_table': 'outbound_packets',
            },
        ),
        migrations.CreateModel(
            name='RefreshSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('cancelled', 'Cancelled')], default='active', max_length=16)),
                ('requested_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('requested_for_all_peers', models.BooleanField(default=False)),
                ('messages_total', models.PositiveIntegerField(default=0)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_sessions', to='directory.contact')),
                ('peer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='directory.user')),
                ('requested_by_inbound', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='messaging.inbounddirectmessage')),
            ],
            options={
                'db_table': 'refresh_sessions',
            },
        ),
        migrations.AddField(
            model_name='messagedelivery',
            name='refresh_session',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='messaging.refreshsession'),
        ),
        migrations.AddIndex(
            model_name='inbounddirectmessage',
            index=models.Index(condition=models.Q(('processing_state', 'received')), fields=['id'], name='inbound_received_id'),
        ),
        migrations.AddIndex(
            model_name='inbounddirectmessage',
            index=models.Index(fields=['contact', 'sender_timestamp'], name='inbound_contact_timestamp'),
        ),
        migrations.AddIndex(
            model_name='inbounddirectmessage',
            index=models.Index(fields=['contact', 'received_at'], name='inbound_contact_received_at'),
        ),
        migrations.AddIndex(
            model_name='inbounddirectmessage',
            index=models.Index(fields=['received_at'], name='inbound_received_at'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'sender', 'accepted_at', 'id'], name='message_refresh_scope'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'client_message_id'], name='message_recipient_client_id'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['accepted_at'], name='message_accepted_at'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(condition=models.Q(('accepted_at__isnull', True)), fields=['last_part_at'], name='message_incomplete_last_part'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('sender', 'client_message_id'), name='message_unique_client_id_per_sender'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('client_message_id__gte', 1), ('client_message_id__lte', 9999999999999999)), name='message_client_id_range'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('part_count__gte', 1), ('part_count__lte', 10)), name='message_part_count_range'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('part_count', models.Func(models.F('part_texts'), function='jsonb_array_length', output_field=models.PositiveSmallIntegerField()))), name='message_part_texts_match_part_count'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accepted_at__isnull', True), ('text__isnull', True)), models.Q(('accepted_at__isnull', False), ('text__isnull', False)), _connector='OR'), name='message_text_set_when_accepted'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('delivered_at__isnull', True), ('accepted_at__isnull', False), _connector='OR'), name='message_delivered_only_when_accepted'),
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.CheckConstraint(condition=models.Q(('read_at__isnull', True), ('delivered_at__isnull', False), _connector='OR'), name='message_read_only_when_delivered'),
        ),
        migrations.AddIndex(
            model_name='receiptnotification',
            index=models.Index(condition=models.Q(('state', 'pending')), fields=['next_attempt_at'], name='receipt_pending_next_attempt'),
        ),
        migrations.AddIndex(
            model_name='receiptnotification',
            index=models.Index(fields=['device', 'state'], name='receipt_device_state'),
        ),
        migrations.AddConstraint(
            model_name='receiptnotification',
            constraint=models.UniqueConstraint(fields=('message', 'device'), name='receipt_notification_unique_per_device'),
        ),
        migrations.AddConstraint(
            model_name='receiptnotification',
            constraint=models.CheckConstraint(condition=models.Q(('confirmed_level__lte', models.F('target_level'))), name='receipt_confirmed_level_at_most_target'),
        ),
        migrations.AddConstraint(
            model_name='receiptnotification',
            constraint=models.CheckConstraint(condition=models.Q(('state', 'cancelled'), models.Q(('confirmed_level', models.F('target_level')), ('state', 'confirmed')), models.Q(models.Q(('state__in', ['cancelled', 'confirmed']), _negated=True), models.Q(('confirmed_level', models.F('target_level')), _negated=True)), _connector='OR'), name='receipt_confirmed_state_matches_levels'),
        ),
        migrations.AddConstraint(
            model_name='receiptnotification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'pending'), _negated=True), ('next_attempt_at__isnull', False), _connector='OR'), name='receipt_pending_has_next_attempt'),
        ),
        migrations.AddIndex(
            model_name='outboundpacket',
            index=models.Index(condition=models.Q(('state__in', ['queued_on_node', 'acknowledgement_timed_out'])), fields=['expected_acknowledgement_code'], name='packet_awaiting_ack_code'),
        ),
        migrations.AddIndex(
            model_name='outboundpacket',
            index=models.Index(condition=models.Q(('acknowledged_at__isnull', True)), fields=['acknowledgement_deadline_at'], name='packet_unacknowledged_deadline'),
        ),
        migrations.AddIndex(
            model_name='outboundpacket',
            index=models.Index(fields=['contact', 'queued_at'], name='packet_contact_queued_at'),
        ),
        migrations.AddIndex(
            model_name='outboundpacket',
            index=models.Index(fields=['prepared_at'], name='packet_prepared_at'),
        ),
        migrations.AddIndex(
            model_name='refreshsession',
            index=models.Index(fields=['device', 'state'], name='refresh_session_device_state'),
        ),
        migrations.AddConstraint(
            model_name='refreshsession',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'active')), fields=('device', 'peer'), name='refresh_single_active_session'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(condition=models.Q(('state', 'pending')), fields=['next_attempt_at'], name='delivery_pending_next_attempt'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['device', 'state'], name='delivery_device_state'),
        ),
        migrations.AddIndex(
            model_name='messagedelivery',
            index=models.Index(fields=['refresh_session', 'state'], name='delivery_session_state'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.UniqueConstraint(fields=('message', 'device'), name='message_delivery_unique_per_device'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.CheckConstraint(condition=models.Q(('round_pending_parts_mask__gte', 0), ('round_pending_parts_mask__lte', 1023)), name='message_delivery_round_mask_range'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.CheckConstraint(condition=models.Q(('parts_received_mask__gte', 0), ('parts_received_mask__lte', 1023)), name='message_delivery_received_mask_range'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'pending'), _negated=True), ('next_attempt_at__isnull', False), _connector='OR'), name='message_delivery_pending_has_next_attempt'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'delivered'), _negated=True), ('delivered_at__isnull', False), _connector='OR'), name='message_delivery_delivered_has_delivered_at'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('state', 'queued_for_refresh'), _negated=True), ('refresh_session__isnull', False), _connector='OR'), name='message_delivery_queued_has_refresh_session'),
        ),
        migrations.AddConstraint(
            model_name='messagedelivery',
            constraint=models.UniqueConstraint(condition=models.Q(('state', 'pending')), fields=('refresh_session',), name='refresh_session_single_head'),
        ),
    ]
