# Generated by Django 6.1.1 on 2026-09-25 14:53

import django.db.models.deletion
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('username_lookup', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Lower('username'), output_field=models.CharField(max_length=16), unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.CheckConstraint(condition=models.Q(('username__regex', '^[A-Za-z0-9]{3,16}$')), name='user_username_format')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_key', models.CharField(max_length=64, unique=True)),
                ('public_key_prefix', models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Left('public_key', 12), output_field=models.CharField(max_length=12), unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('node_type', models.PositiveSmallIntegerField(default=1)),
                ('advert_timestamp', models.BigIntegerField(default=0)),
                ('latitude_microdegrees', models.IntegerField(default=0)),
                ('longitude_microdegrees', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('card', 'Contact card'), ('pairing', 'Pairing')], max_length=16)),
                ('card_uri', models.TextField(blank=True, default='')),
                ('added_at', models.DateTimeField()),
                ('linked_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('failed_sign_in_count', models.PositiveSmallIntegerField(default=0)),
                ('failed_sign_in_window_started_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('node_sync_state', models.CharField(choices=[('pending_add', 'Waiting to be added to the node'), ('on_node', 'On the node'), ('add_failed', 'Adding to the node failed')], default='pending_add', max_length=16)),
                ('node_sync_error', models.TextField(blank=True, default='')),
                ('node_synced_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('node_name', models.CharField(blank=True, default='', max_length=64)),
                ('node_out_path_length', models.SmallIntegerField(blank=True, default=None, null=True)),
                ('last_heard_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('last_path_update_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='directory.user')),
            ],
            options={
                'db_table': 'contacts',
                'indexes': [models.Index(fields=['node_sync_state'], name='contact_node_sync_state')],
                'constraints': [models.CheckConstraint(condition=models.Q(('public_key__regex', '^[0-9a-f]{64}$')), name='contact_public_key_format'), models.CheckConstraint(condition=models.Q(('node_type', 1)), name='contact_node_type_chat'), models.CheckConstraint(condition=models.Q(models.Q(('linked_at__isnull', True), ('user__isnull', True)), models.Q(('linked_at__isnull', False), ('user__isnull', False)), _connector='OR'), name='contact_linked_at_matches_user')],
            },
        ),
    ]
